### ISSUE TITLE
(Bug) Users can delete other users comments

### ISSUE THREAD

**Issue by stroz08** [info442-spr22/b-team#101] opened 2022-05-18 16:50 UTC
Severity: minor
Summary: Users can delete comments made by other users.
Environment: Google Chrome Version 101.0.4951.67, Windows 10
Steps to reproduce: Walk up to somebody's comment and completely destroy it by clicking delete
Expected result: Other users would have no authority to delete other users comments
Actual result: Other users have full authority to delete comments by other users

**Comment by jeannechoi00** [comment] 2022-05-23 16:39
- Duplicate of #81

**Closed by jeannechoi00** 2022-05-23 16:39 UTC
Labels: Duplicate
